version: '3.8'

services:
  laravel:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  nextjs:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - laravel
